packages:
  - "ember/*"

allowBuilds:
  "@parcel/watcher": false
  esbuild: true

# we don't want addons to be bad citizens of the ecosystem
autoInstallPeers: false

# we want true isolation, if a dependency is not declared, we want an error
resolvePeersFromWorkspaceRoot: false

# branches where packages are published
publishBranch: dev
