name: pr title check

on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened]

jobs:
  lint-pr-title:
    runs-on: ubuntu-26
    steps:
      - uses: 1024pix/pix-actions/check-pr-title@main
