name: Release Nebulix Ember

permissions:
  id-token: write # necessary for publishing to npm
  pull-requests: write # necessary for writing comment on PR

on:
  workflow_dispatch:

jobs:
  release:
    name: "Release Nebulix Ember"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/setup@v2
        with:
          cache: true

      - name: Setup npm auth
        run: pnpm config set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
        env:
          NPM_TOKEN: ${{ secrets.TMP_NPM_TOKEN }}

      - name: Publish
        run: pnpm publish --filter @1024pix/nebulix-ember --access=public
        env:
          GITHUB_TOKEN: ${{ secrets.PIX_SERVICE_ACTIONS_TOKEN }}
